export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const ADD_CHILLER = 'ADD_CHILLER';
export const CHILLER_ERROR = 'CHILLER_ERROR';
export const FETCH_CHILLERS = 'FETCH_CHILLERS';
export const FETCH_RECENT = 'FETCH_RECENT';
